### ISSUE TITLE
bug: ArrayList API migration incomplete - 17+ files need updating

### ISSUE THREAD

**Issue by yusa-imit** [yusa-imit/zuda#6]
## Problem
Multiple files in the codebase still use the old Zig 0.13 ArrayList API, which doesn't compile in Zig 0.15.2.

## Root Cause
Zig 0.15 changed the ArrayList API:
- **Removed**: `ArrayList(T).init(allocator)`
- **New syntax**: `var list: ArrayList(T) = .{}` or `ArrayList(T){}`
- **Methods now take allocator**: `append(allocator, item)`, `deinit(allocator)`, `clone(allocator)`

## Affected Files
```bash
grep -r "ArrayList.*\.init(" src/ --include="*.zig" -l
```

Found 18 files (17 remaining after DancingLinks fix in eb13995):
- src/algorithms/graph/*.zig (11 files)
- src/containers/hashing/consistent_hash_ring.zig
- src/containers/graphs/*.zig (3 files)
- src/containers/heaps/*.zig (3 files)

## Impact
- Tests for these files will fail/crash
- Some tests may not run at all due to compilation errors
- CI may pass because root.zig only does ref check, not actual test execution

## Fix Pattern
From `.claude/memory/patterns.md`:
```zig
// OLD (0.13):
var list = std.ArrayList(T).init(allocator);
try list.append(item);
list.deinit();

// NEW (0.15):
var list: std.ArrayList(T) = .{};
try list.append(allocator, item);
list.deinit(allocator);
```

## Next Steps
1. Systematically fix each file
2. Run `zig test <file>` after each fix
3. Ensure tests pass before committing
4. Consider adding a check to CI to catch this pattern

## References
- Commit eb13995: DancingLinks migration (tests still failing due to algorithm bug)
- Memory doc: `.claude/memory/patterns.md`
