### ISSUE TITLE
bug: NDArray module incompatible with Zig 0.15.x (std.meta.trait deprecated)

### ISSUE THREAD

**Issue by yusa-imit** [yusa-imit/zuda#15]
**Describe the bug**
NDArray module fails to compile with Zig 0.15.x due to deprecated `std.meta.trait` API usage.

**Compilation Errors**
1. `std.meta.trait.isFloat/isIntegral` is deprecated in Zig 0.15.x (14 occurrences in ndarray.zig)
2. Integer subtraction type errors in arange() (line 363, 368)
3. HashMap trying to hash f64/f32 types (needs custom hash functions)
4. Test code issues: const pointers passed to deinit(), transpose() not returning error union, dimension mismatches

**Root Cause**
Zig 0.15.x removed `std.meta.trait` module. Modern Zig uses `@typeInfo(T)` pattern.

**Fix Required**
Replace all `std.meta.trait` usages with `@typeInfo` pattern:
```zig
// Old (Zig 0.14.x):
if (!std.meta.trait.isFloat(T)) { ... }

// New (Zig 0.15.x):
if (@typeInfo(T) != .float) { ... }
// or for integral: @typeInfo(T) != .int
```

**Impact**
- Blocks full test suite execution (127 compilation errors)
- NDArray module and all dependent tests cannot run
- Hypothesis testing module (v1.22.0) tests blocked

**Files Affected**
- `src/ndarray/ndarray.zig` (14 occurrences of std.meta.trait, type casting issues)
- Test code within ndarray.zig (const/mut pointer issues, error union handling)

**Reference**
Same fix already applied successfully in `src/stats/descriptive.zig` (commit b1886b8).
