### ISSUE TITLE
bug: compat.zr_dag incompatible with Zig 0.15 - toOwnedSlice requires allocator

### ISSUE THREAD

**Issue by yusa-imit** [yusa-imit/zuda#23]
## Symptom
`zuda.compat.zr_dag.DAG.topologicalSort()` and `detectCycle()` fail to compile with Zig 0.15.2 due to `toOwnedSlice()` API change.

## Error
```
src/compat/zr_dag.zig:224:28: error: member function expected 1 argument(s), found 0
return result.order.toOwnedSlice();
       ~~~~~~~~~~~~^~~~~~~~~~~~~
```

## Cause
Zig 0.15 changed `ArrayList.toOwnedSlice()` to require an allocator parameter:
- **Old (0.14)**: `list.toOwnedSlice()`
- **New (0.15)**: `list.toOwnedSlice(allocator)`

## Affected Code
- `src/compat/zr_dag.zig:224` in `topologicalSort()`
- `src/compat/zr_dag.zig:259` in `detectCycle()`

## Expected Fix
```zig
// Line 224
return result.order.toOwnedSlice(self.allocator);

// Line 259
return cv.toOwnedSlice(self.allocator);
```

## Environment
- **zuda**: v2.0.3
- **Zig**: 0.15.2
- **Project**: zr (task runner)
- **Reporter**: from:zr

## Impact
Blocks migration of zr's graph algorithms to zuda.compat.zr_dag layer.

**Comment by yusa-imit** [comment]
Fixed in f95785b - Added allocator parameter to toOwnedSlice() calls for Zig 0.15 compatibility in topologicalSort() and detectCycle().
